{% set version = "1.1.4" %}
{% set github_repo = "https://github.com/matuskosut" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bgen
  version: "{{ version|replace("-", "_") }}"

source:
  url: {{ github_repo }}/rbgen/releases/download/{{ version }}/rbgen_{{ version }}.tar.gz
  sha256: 92bfe2b7ae077b676fe959d49fe8f81f8b23d8f92a021ea7b9cb8525958466b1

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    # - {{ compiler('c') }}                     # [not win]
    # - {{ compiler('m2w64_c') }}               # [win]
    - {{ compiler('cxx') }}                   # [not win]
    - {{ compiler('m2w64_cxx') }}             # [win]
    # - {{ posix }}filesystem                   # [win]
    # - {{ posix }}sed                          # [win]
    # - {{ posix }}coreutils                    # [win]
    # - {{ posix }}zip                          # [win]
    # - {{ posix }}make
    - r-base
    - boost <=1.63.0
    - boost-cpp <=1.63.0
    - sqlite 3.9.2 1
  host:
    - r-base
    - r-rcpp
    - boost-cpp <=1.63.0
    - sqlite 3.9.2 1
  run:
    - {{ native }}gcc-libs                    # [win]
    - r-base
    - r-rcpp
    - zstd
    - boost-cpp <=1.63.0
    - sqlite 3.9.2 1

test:
  source_files:
    - test.sh
    - example/
    - example/*.bgen
    - example/*.bgi
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rbgen')"
    - bash test.sh $R                         # [not win]

about:
  home: https://enkre.net/cgi-bin/code/bgen
  summary: R interface to BGEN files


# Package: rbgen
# Type: Package
# Title: R interface to BGEN files
# Version: 1.1.4
# Date: 2018-08-03
# Author: Gavin Band
# Maintainer: Gavin Band <gavin.band@well.ox.ac.uk>
# Description: This package provides functions to load data from an indexed BGEN file.
# License: Boost Software License Version 1.0 (http://www.boost.org/LICENSE_1_0.txt)
# Imports: Rcpp (>= 0.12.4)
# LinkingTo: Rcpp
