{% set version="3.9.2" %}
{% set year="2015" %}
{% set version_split=version.split(".") %}
{% set major=version_split[0] %}
{% set minor=version_split[1]|int * 10 %}
{% set bugfix=version_split[2]|int * 100 %}
{% set version_coded=(major ~ (("%03d" % minor)|string) ~ (("%03d" % bugfix)|string)) %}

package:
  name: sqlite
  version: {{ version }}

source:
  fn: sqlite-autoconf-{{ version_coded }}.tar.gz
  url: https://www.sqlite.org/{{ year }}/sqlite-autoconf-{{ version_coded }}.tar.gz
  sha1: dae1ae5297fece9671ae0c434a7ecd0cda09c76a

build:
  number: 1
  # features:
  #   - vc9    # [win and py27]
  #   - vc10   # [win and py34]
  #   - vc14   # [win and py35]
  run_exports:
    # sometimes adds new symbols.  Default behavior is OK.
    #    https://abi-laboratory.pro/tracker/timeline/sqlite/
    - {{ pin_subpackage('sqlite') }}

requirements:
  build:
    # python is for lining up vc feature (runtime)
    # - python      # [win]
    - {{ compiler('c') }}        # [not win]
    # - {{ compiler('m2w64_c') }}  # [win]
    - make        # [not win]
    - libtool     # [not win]
  # host:
  #   - ncurses     # [not win]
  #   - readline    # [not win]
  #   - zlib        # [not win]
  # run:
  #   - ncurses     # [not win]
  #   - readline    # [not win]

test:
  # requires:
  #   - python  2.7*     # [win and py27]
  #   - python  3.4*     # [win and py34]
  #   - python  3.5*     # [win and py35]
  commands:
    - sqlite3 --version
    - if not exist %PREFIX%\\Library\bin\sqlite3.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\lib\sqlite3.lib exit 1  # [win]
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}  # [not win]
    - test ! -f $PREFIX/lib/libsqlite3.a  # [not win]
    - if not exist %PREFIX%\\Library\include\sqlite3.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\include\sqlite3ext.h exit 1  # [win]
    - test -f $PREFIX/include/sqlite3.h  # [not win]
    - test -f $PREFIX/include/sqlite3ext.h  # [not win]

about:
  home: http://www.sqlite.org/
  license: Public-Domain (http://www.sqlite.org/copyright.html)
  license_family: Public-Domain
  summary: implements a self-contained, zero-configuration, SQL database engine

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
